/**
 * Writes public/__forms.html — the static stub Netlify's build-time scanner
 * reads to learn which forms (and which fields) exist. The real forms are
 * rendered by React, which Netlify can't see, so the stub has to list every
 * field. Because form fields are editable in the CMS, this file is GENERATED
 * from the same content on every `npm run build` / `npm run dev`; never edit
 * public/__forms.html by hand.
 *
 * Sources: content/forms.json, content/services/items/*.json, and the
 * "leave-a-review" form.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const readJson = (rel) => JSON.parse(readFileSync(join(root, rel), "utf8"));
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");

const forms = readJson("content/forms.json");
const servicesDir = "content/services/items";
const services = readdirSync(join(root, servicesDir))
  .filter((f) => f.endsWith(".json"))
  .sort()
  .map((f) => readJson(`${servicesDir}/${f}`));

const fieldLine = (f) =>
  f.type === "textarea"
    ? `<textarea name="${esc(f.name)}"></textarea>`
    : `<input type="${esc(f.type || "text")}" name="${esc(f.name)}" />`;

const productLines = [`<input type="checkbox" name="products" />`, `<input type="text" name="other_product" />`];

const blocks = [];
const seen = new Set();

function addForm({ name, multipart = false, lines }) {
  if (!name) throw new Error("generate-forms: a form has no name (check each service's Netlify Form Name).");
  if (seen.has(name)) throw new Error(`generate-forms: two forms share the name "${name}".`);
  seen.add(name);
  const names = lines.map((l) => l.match(/name="([^"]+)"/)?.[1]).filter(Boolean);
  const dup = names.find((n, i) => names.indexOf(n) !== i);
  if (dup) throw new Error(`generate-forms: form "${name}" has two fields called "${dup}".`);
  blocks.push(
    [
      `    <form name="${esc(name)}" data-netlify="true" data-netlify-honeypot="bot-field"${
        multipart ? ' enctype="multipart/form-data"' : ""
      } hidden>`,
      `      <input type="hidden" name="form-name" value="${esc(name)}" />`,
      `      <input name="bot-field" />`,
      ...lines.map((l) => `      ${l}`),
      `    </form>`,
    ].join("\n")
  );
}

// One inquiry form per service
for (const s of services) {
  addForm({
    name: s.formName,
    multipart: !!s.formUpload,
    lines: [
      ...forms.inquiryForm.fields.map(fieldLine),
      ...(s.hasProductsPicker ? productLines : []),
      ...(s.formUpload ? [`<input type="file" name="photos" />`] : []),
    ],
  });
}

// General "Start a project" form
const projectTypes = [...services.map((s) => s.title), forms.startProjectForm.notSureLabel];
addForm({
  name: "start-a-project",
  lines: [
    ...forms.startProjectForm.fields.map(fieldLine),
    `<select name="project_type">${projectTypes.map((t) => `<option>${esc(t)}</option>`).join("")}</select>`,
    ...(services.some((s) => s.hasProductsPicker) ? productLines : []),
  ],
});

// Customer review form (optional photo → multipart)
addForm({
  name: "leave-a-review",
  multipart: true,
  lines: [...forms.reviewForm.fields.map(fieldLine), `<input type="file" name="photo" />`],
});

const html = `<!doctype html>
<html>
  <head><title>Netlify form detection</title></head>
  <body>
    <!--
      GENERATED by scripts/generate-forms.mjs from content/forms.json and
      content/services/items/*.json — do not edit by hand. Netlify's build-time
      parser only sees static HTML, not React-rendered markup, so these stubs
      exist solely to register every form and field.
    -->
${blocks.join("\n\n")}
  </body>
</html>
`;

writeFileSync(join(root, "public/__forms.html"), html);
console.log(`generate-forms: wrote public/__forms.html (${blocks.length} forms)`);
